language: java
jdk:
  - openjdk7
  - oraclejdk8
sudo: false
before_install:
  - cp ./etc/settings.xml ~/.m2/
  - cp ./etc/onTravisBuildFailure.sh  ~/
  - cp ./etc/onTravisBuildSuccess.sh  ~/
  - chmod 777 ~/onTravisBuildFailure.sh
  - chmod 777 ~/onTravisBuildSuccess.sh
script:
  - mvn -B clean verify
after_failure: ~/onTravisBuildFailure.sh
after_success: ~/onTravisBuildSuccess.sh
after_script:
  - mvn clean -DsourceEncoding=UTF-8 cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#esbmessageadmin
    on_success: always
env:
  global:
  - secure: v3vt2PXOlNDjSdVeUeS1i94S3ECkfiedh1v1Z+VLc4nyPh1vMGnIGTwGw3Ewz4RoG7YKljuTdANoMEcV9MA//DbGNren2IKXj80kmFnTJdX+S2Cklzf3Yl18LPFZZiPHMeqy8VyzdO+2UYaDlBAcYXA0rhE/l6dhNjmzH7B4PHI=
  - secure: hQslpNik0OSdzreoN9cTdF6Pj0FcH31rZpN4Y2K2vNfjGuVQ61041BLmVVdlCy/qU1rEBunyMHYH5Y/sNnpQbolOhRE9PnFhODyvde1Ut8ZD63LDGBtvXxovQv1LYmy+YO5FDQ1ESMXKEP6FFXnKaoAee/OTDGIskOSNQmQsaY8=
